/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafico;

/**
 *
 * @author Casa
 */
public class menuDadosSaude extends javax.swing.JFrame {

    /**
     * Creates new form welcomeScreen
     */
    public menuDadosSaude() {
        initComponents();
        
        // Tamanho do JFrame
        setSize(500, 400);
        // Bloquear a possibilidade de fazer resize
        setResizable(false);
        // Pre-definir o que faz o botao de fecho
        setDefaultCloseOperation(menuDadosSaude.EXIT_ON_CLOSE);
        // Centralizar o JFrame no meio da tela
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoIMC = new javax.swing.JButton();
        botaoIAC = new javax.swing.JButton();
        botaoPG = new javax.swing.JButton();
        botaoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitness APP - Movimenta-te");
        setBackground(jLabel1.getBackground());
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha uma das opções:");
        getContentPane().add(jLabel1);

        botaoIMC.setText("CÁLCULO DO SEU ÍNDICE DE MASSA CORPORAL (I.M.C.)");
        botaoIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIMCActionPerformed(evt);
            }
        });
        getContentPane().add(botaoIMC);

        botaoIAC.setText("CÁLCULO DO SEU ÍNDICE DE ADIPOSIDADE CORPORAL (I.A.C)");
        botaoIAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIACActionPerformed(evt);
            }
        });
        getContentPane().add(botaoIAC);

        botaoPG.setText("CÁLCULO DO SEU PERCENTUAL DE GORDURA (P.G)");
        botaoPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPGActionPerformed(evt);
            }
        });
        getContentPane().add(botaoPG);

        botaoMenu.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        botaoMenu.setText("VOLTAR AO MENU INICIAL");
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPGActionPerformed
        dispose();
        saudePercGordura.main();
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPGActionPerformed

    private void botaoIACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIACActionPerformed
        dispose();
        saudeIAC.main();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoIACActionPerformed

    private void botaoIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIMCActionPerformed
        dispose();
        saudeIMC.main();
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoIMCActionPerformed

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        dispose();
        primeiroMenu.main();
    }//GEN-LAST:event_botaoMenuActionPerformed


    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDadosSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDadosSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDadosSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDadosSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menuDadosSaude().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIAC;
    private javax.swing.JButton botaoIMC;
    private javax.swing.JButton botaoMenu;
    private javax.swing.JButton botaoPG;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
