/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafico;


/**
 *
 * @author Casa
 */
public class menuTreinoPersonalizado extends javax.swing.JFrame {

    /**
     * Creates new form welcomeScreen
     */
    public menuTreinoPersonalizado() {
        initComponents();
        
        // Tamanho do JFrame
        setSize(500, 400);
        // Bloquear a possibilidade de fazer resize
        setResizable(false);
        // Pre-definir o que faz o botao de fecho
        setDefaultCloseOperation(menuTreinoPersonalizado.EXIT_ON_CLOSE);
        // Centralizar o JFrame no meio da tela
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoTreinoCardio = new javax.swing.JButton();
        botaoTreinoFlexibilidade = new javax.swing.JButton();
        botaoTreinoPrepFisica = new javax.swing.JButton();
        botaoTreinoMuscula = new javax.swing.JButton();
        botaoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitness APP - Movimenta-te");
        setBackground(jLabel1.getBackground());
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha uma das opções:");
        getContentPane().add(jLabel1);

        botaoTreinoCardio.setText("TREINO CARDIO");
        botaoTreinoCardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTreinoCardioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTreinoCardio);

        botaoTreinoFlexibilidade.setText("TREINO FLEXIBILIDADE");
        botaoTreinoFlexibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTreinoFlexibilidadeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTreinoFlexibilidade);

        botaoTreinoPrepFisica.setText("TREINO PREPARAÇÃO FÍSICA");
        botaoTreinoPrepFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTreinoPrepFisicaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTreinoPrepFisica);

        botaoTreinoMuscula.setText("TREINO MUSCULAÇÃO");
        botaoTreinoMuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTreinoMusculaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTreinoMuscula);

        botaoMenu.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        botaoMenu.setText("VOLTAR AO MENU INICIAL");
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTreinoFlexibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTreinoFlexibilidadeActionPerformed
        dispose();
        outputTreinoPersonalizado.main("Flexibilidade");
    }//GEN-LAST:event_botaoTreinoFlexibilidadeActionPerformed

    private void botaoTreinoMusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTreinoMusculaActionPerformed
        dispose();
        menuTreinoMusculacao.main();
    }//GEN-LAST:event_botaoTreinoMusculaActionPerformed

    private void botaoTreinoCardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTreinoCardioActionPerformed
        dispose();
        outputTreinoPersonalizado.main("Cardio");
    }//GEN-LAST:event_botaoTreinoCardioActionPerformed

    private void botaoTreinoPrepFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTreinoPrepFisicaActionPerformed
        dispose();
        menuTreinoPrepFisica.main();        
// TODO add your handling code here:
    }//GEN-LAST:event_botaoTreinoPrepFisicaActionPerformed

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        dispose();
        primeiroMenu.main();
    }//GEN-LAST:event_botaoMenuActionPerformed


    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuTreinoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuTreinoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuTreinoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuTreinoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuTreinoPersonalizado().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMenu;
    private javax.swing.JButton botaoTreinoCardio;
    private javax.swing.JButton botaoTreinoFlexibilidade;
    private javax.swing.JButton botaoTreinoMuscula;
    private javax.swing.JButton botaoTreinoPrepFisica;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
