/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafico;


/**
 *
 * @author Casa
 */
public class primeiroMenu extends javax.swing.JFrame {

    /**
     * Creates new form welcomeScreen
     */
    public primeiroMenu() {
        initComponents();
        
        // Tamanho do JFrame
        setSize(500, 400);
        // Bloquear a possibilidade de fazer resize
        setResizable(false);
        // Pre-definir o que faz o botao de fecho
        setDefaultCloseOperation(primeiroMenu.EXIT_ON_CLOSE);
        // Centralizar o JFrame no meio da tela
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoTreinoDiario = new javax.swing.JButton();
        botaoTreinoEspecializado = new javax.swing.JButton();
        botaoSaude = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitness APP - Movimenta-te");
        setBackground(jLabel1.getBackground());
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha uma das opções:");
        getContentPane().add(jLabel1);

        botaoTreinoDiario.setText("TREINO DIÁRIO");
        botaoTreinoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTreinoDiarioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTreinoDiario);

        botaoTreinoEspecializado.setText("TREINO ESPECIALIZADO");
        botaoTreinoEspecializado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTreinoEspecializadoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoTreinoEspecializado);

        botaoSaude.setText("TESTE A SUA SAÚDE");
        botaoSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSaude);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoTreinoEspecializadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTreinoEspecializadoActionPerformed
        dispose();
        menuTreinoPersonalizado.main();
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoTreinoEspecializadoActionPerformed

    private void botaoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSaudeActionPerformed
        dispose();
        menuDadosSaude.main();
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSaudeActionPerformed

    private void botaoTreinoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTreinoDiarioActionPerformed
        dispose();
        outputTreinoDiario.main();
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoTreinoDiarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(primeiroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(primeiroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(primeiroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(primeiroMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new primeiroMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSaude;
    private javax.swing.JButton botaoTreinoDiario;
    private javax.swing.JButton botaoTreinoEspecializado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
