/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafico;

import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import javax.swing.Timer;
import personaltraining_app.services.UsuariosService;
import personaltraining_app.exercicios.Usuario;

public class saudeIAC extends javax.swing.JFrame {
    
    public saudeIAC() {
        initComponents();
        
        // Tamanho do JFrame
        setSize(500, 400);
        // Bloquear a possibilidade de fazer resize
        setResizable(false);
        // Pre-definir o que faz o botao de fecho
        setDefaultCloseOperation(saudeIAC.EXIT_ON_CLOSE);
        // Centralizar o JFrame no meio da tela
        setLocationRelativeTo(null);
        
        outputTextoIAC.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelAltura = new javax.swing.JLabel();
        inputAltura = new javax.swing.JTextField();
        labelCentimetros = new javax.swing.JLabel();
        labelCentimetros2 = new javax.swing.JLabel();
        labelQuadril = new javax.swing.JLabel();
        inputQuadril = new javax.swing.JTextField();
        outputIAC = new javax.swing.JLabel();
        botaoCalculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextoIAC = new javax.swing.JTextArea();
        voltarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoHomem = new javax.swing.JRadioButton();
        botaoMulher = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitness APP - Movimenta-te");
        setBackground(jLabel1.getBackground());
        setResizable(false);

        labelAltura.setText("Qual é a sua altura?");

        inputAltura.setAutoscrolls(false);
        inputAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlturaActionPerformed(evt);
            }
        });

        labelCentimetros.setText("(em cm)");

        labelCentimetros2.setText("(em cm)");

        labelQuadril.setText("Qual é a da circunferência do seu quadril?");

        inputQuadril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQuadrilActionPerformed(evt);
            }
        });

        outputIAC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        outputIAC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoCalculo.setText("Calcular I.A.C.");
        botaoCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalculoActionPerformed(evt);
            }
        });

        outputTextoIAC.setEditable(false);
        outputTextoIAC.setColumns(20);
        outputTextoIAC.setLineWrap(true);
        outputTextoIAC.setRows(5);
        outputTextoIAC.setWrapStyleWord(true);
        outputTextoIAC.setBorder(null);
        outputTextoIAC.setOpaque(false);
        outputTextoIAC.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(outputTextoIAC);

        voltarMenu.setText("Voltar ao Menu Inicial");
        voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuActionPerformed(evt);
            }
        });

        buttonGroup1.add(botaoHomem);
        botaoHomem.setSelected(true);
        botaoHomem.setText("Homem");
        botaoHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHomemActionPerformed(evt);
            }
        });

        buttonGroup1.add(botaoMulher);
        botaoMulher.setText("Mulher");
        botaoMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMulherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(voltarMenu)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoCalculo)
                                        .addGap(53, 53, 53)
                                        .addComponent(botaoHomem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoMulher))
                                    .addComponent(outputIAC)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(labelQuadril, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelAltura)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputQuadril)
                            .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCentimetros2)
                            .addComponent(labelCentimetros))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCentimetros)
                    .addComponent(labelAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQuadril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCentimetros2)
                    .addComponent(labelQuadril))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoHomem)
                    .addComponent(botaoMulher)
                    .addComponent(botaoCalculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(outputIAC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltarMenu)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlturaActionPerformed

    private void inputQuadrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQuadrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQuadrilActionPerformed

    private void botaoCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalculoActionPerformed
    
        // TODO add your handling code here:

        // limitar a inserção dos dados de peso entre 3 e 225kg e limitar a inserção da altura entre 45 e 225cm
        if (inputQuadril.getText().isEmpty() || inputAltura.getText().isEmpty() || Double.parseDouble(inputQuadril.getText()) < 0 || Double.parseDouble(inputQuadril.getText()) > 200 || Double.parseDouble(inputAltura.getText()) < 45 || Double.parseDouble(inputAltura.getText()) > 225){
            outputIAC.setForeground(new java.awt.Color(255, 0, 51)); // o aviso passa a ter cor vermelha
            outputIAC.setText("      Dados Inválidos");
            outputTextoIAC.setVisible(false);
            piscapisca(); //alerta visual de dados invalidos
        }
        
        else{
            Usuario usuario = new Usuario(0,Double.parseDouble(inputAltura.getText()),0,Double.parseDouble(inputQuadril.getText()),0);
            UsuariosService userservice = new UsuariosService();
            
            if (botaoHomem.isSelected()){
                userservice.calcularIAC(usuario, "homem");
            }
            if (botaoMulher.isSelected()){
                userservice.calcularIAC(usuario, "mulher");
            }
            
            outputIAC.setForeground(new java.awt.Color(0, 0, 0)); // o output mantem (ou muda) para coloração a preto
            String iac = new DecimalFormat("#.0#").format(userservice.getIac());
            
            outputIAC.setText("O seu I.A.C. é de " + iac);
            outputTextoIAC.setVisible(true);
            outputTextoIAC.setText(userservice.getEstadoIAC());
            outputTextoIAC.setCaretPosition(0);
        }
    }//GEN-LAST:event_botaoCalculoActionPerformed

    private void voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuActionPerformed
        dispose();
        primeiroMenu.main();
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarMenuActionPerformed

    private void botaoHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoHomemActionPerformed

    private void botaoMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMulherActionPerformed

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saudeIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saudeIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saudeIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saudeIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saudeIAC().setVisible(true);

            }
        });
    }
    
    private void piscapisca() {
        
        final Timer[] temporizador = {new Timer(500, null)}; // Declaração final e inicialização do Timer
        int[] contador = {0}; // contador para controlar o número de vezes que a label piscou
        temporizador[0] = new Timer(500, (ActionEvent e) -> {
            outputIAC.setVisible(!outputIAC.isVisible()); // Inverte a visibilidade da JLabel
            contador[0]++; // Incrementa o contador
            if (contador[0] >= 10) { // Se a label piscar 10 vezes
                temporizador[0].stop(); // Para o temporizador
            }
        });
        temporizador[0].start();    
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalculo;
    private javax.swing.JRadioButton botaoHomem;
    private javax.swing.JRadioButton botaoMulher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputAltura;
    private javax.swing.JTextField inputQuadril;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCentimetros;
    private javax.swing.JLabel labelCentimetros2;
    private javax.swing.JLabel labelQuadril;
    private javax.swing.JLabel outputIAC;
    private javax.swing.JTextArea outputTextoIAC;
    private javax.swing.JButton voltarMenu;
    // End of variables declaration//GEN-END:variables
}
