/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafico;

import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import javax.swing.Timer;
import personaltraining_app.services.UsuariosService;
import personaltraining_app.exercicios.Usuario;

public class saudePercGordura extends javax.swing.JFrame {
    
    public saudePercGordura() {
        initComponents();
        
        // Tamanho do JFrame
        setSize(500, 400);
        // Bloquear a possibilidade de fazer resize
        setResizable(false);
        // Pre-definir o que faz o botao de fecho
        setDefaultCloseOperation(saudePercGordura.EXIT_ON_CLOSE);
        // Centralizar o JFrame no meio da tela
        setLocationRelativeTo(null);
        
        outputInfoPG.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesTipo = new javax.swing.ButtonGroup();
        botaoHomem = new javax.swing.JRadioButton();
        botaoMulher = new javax.swing.JRadioButton();
        labelAltura = new javax.swing.JLabel();
        inputAltura = new javax.swing.JTextField();
        labelCentimetros = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        inputPeso = new javax.swing.JTextField();
        labelKilogramas = new javax.swing.JLabel();
        outputPG = new javax.swing.JLabel();
        voltarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelCircCintura = new javax.swing.JLabel();
        circCintura = new javax.swing.JTextField();
        labelCircQuadril = new javax.swing.JLabel();
        circQuadril = new javax.swing.JTextField();
        labelCircPescoco = new javax.swing.JLabel();
        circPescoco = new javax.swing.JTextField();
        botaoCalculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputInfoPG = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitness APP - Movimenta-te");
        setBackground(jLabel1.getBackground());
        setResizable(false);

        grupoBotoesTipo.add(botaoHomem);
        botaoHomem.setSelected(true);
        botaoHomem.setText("Homem");
        botaoHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHomemActionPerformed(evt);
            }
        });

        grupoBotoesTipo.add(botaoMulher);
        botaoMulher.setText("Mulher");
        botaoMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMulherActionPerformed(evt);
            }
        });

        labelAltura.setText("Qual é a sua altura?");

        inputAltura.setAutoscrolls(false);
        inputAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlturaActionPerformed(evt);
            }
        });

        labelCentimetros.setText("(em cm)");

        labelPeso.setText("Qual é o seu peso ?");

        inputPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPesoActionPerformed(evt);
            }
        });

        labelKilogramas.setText("(em Kg)");

        outputPG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        outputPG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        voltarMenu.setText("Voltar ao Menu Inicial");
        voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuActionPerformed(evt);
            }
        });

        labelCircCintura.setText("Qual é a medida da circunferência da sua cintura?");

        circCintura.setAutoscrolls(false);
        circCintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circCinturaActionPerformed(evt);
            }
        });

        labelCircQuadril.setText("Qual é a medida da circunferência do seu quadril?");

        circQuadril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circQuadrilActionPerformed(evt);
            }
        });

        labelCircPescoco.setText("Qual é a medida da circunferência do seu pescoço?");

        circPescoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circPescocoActionPerformed(evt);
            }
        });

        botaoCalculo.setText("Calcular P.G.");
        botaoCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalculoActionPerformed(evt);
            }
        });

        outputInfoPG.setColumns(20);
        outputInfoPG.setLineWrap(true);
        outputInfoPG.setRows(5);
        jScrollPane1.setViewportView(outputInfoPG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCircCintura)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelPeso)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputPeso))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelAltura)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCentimetros)
                                            .addComponent(labelKilogramas))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(circCintura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botaoHomem)
                                            .addComponent(botaoMulher)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCircPescoco)
                                    .addComponent(labelCircQuadril))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(circQuadril, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(circPescoco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCalculo)
                                .addGap(18, 18, 18)
                                .addComponent(outputPG, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(voltarMenu)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAltura)
                    .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCentimetros)
                    .addComponent(botaoHomem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(inputPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKilogramas)
                    .addComponent(botaoMulher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCircCintura)
                    .addComponent(circCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCircQuadril)
                    .addComponent(circQuadril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCircPescoco)
                    .addComponent(circPescoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCalculo)
                    .addComponent(outputPG))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(voltarMenu)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlturaActionPerformed

    private void inputPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPesoActionPerformed

    private void voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuActionPerformed
        dispose();
        primeiroMenu.main();
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarMenuActionPerformed

    private void circCinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circCinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circCinturaActionPerformed

    private void circQuadrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circQuadrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circQuadrilActionPerformed

    private void circPescocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circPescocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circPescocoActionPerformed

    private void botaoCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalculoActionPerformed
                // TODO add your handling code here:

        // limitar a inserção dos dados de peso entre 3 e 225kg e limitar a inserção da altura entre 45 e 225cm
        if (inputPeso.getText().isEmpty() || inputAltura.getText().isEmpty() 
                || circCintura.getText().isEmpty() || circQuadril.getText().isEmpty() || circPescoco.getText().isEmpty()
                || Double.parseDouble(inputPeso.getText()) < 3 || Double.parseDouble(inputPeso.getText()) > 225 
                || Double.parseDouble(inputAltura.getText()) < 45 || Double.parseDouble(inputAltura.getText()) > 225
                || Double.parseDouble(circCintura.getText()) <= 0 || Double.parseDouble(circQuadril.getText()) <= 0 || Double.parseDouble(circPescoco.getText()) <= 0
                ){
            outputInfoPG.setVisible(false);
            outputPG.setForeground(new java.awt.Color(255, 0, 51)); // o aviso passa a ter cor vermelha
            outputPG.setText("      Dados Inválidos");
            piscapisca(); //alerta visual de dados invalidos
        }
       
        else{
            Usuario usuario = new Usuario(Double.parseDouble(inputPeso.getText()), Double.parseDouble(inputAltura.getText()), Double.parseDouble(circCintura.getText()), Double.parseDouble(circQuadril.getText()), Double.parseDouble(circPescoco.getText()));
            UsuariosService userservice = new UsuariosService();
            if (botaoHomem.isSelected()){
                userservice.calcularPercentualGordura(usuario, "homem");
            }
            if (botaoMulher.isSelected()){
                userservice.calcularPercentualGordura(usuario, "mulher");
            }

            outputPG.setForeground(new java.awt.Color(0, 0, 0)); // o output mantem (ou muda) para coloração a preto
            
            String PG = new DecimalFormat("#.0#").format(userservice.getPercentualGordura());           
            outputPG.setText("Percentual de Gordura estimado é de " + PG);
            outputInfoPG.setVisible(true);
            outputInfoPG.setText(userservice.getEstadoPG());
            outputInfoPG.setCaretPosition(0);
        }
          
    }//GEN-LAST:event_botaoCalculoActionPerformed

    private void botaoHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoHomemActionPerformed

    private void botaoMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoMulherActionPerformed

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saudePercGordura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saudePercGordura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saudePercGordura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saudePercGordura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new saudePercGordura().setVisible(true);
        });
    }
    
    private void piscapisca() {
        
        final Timer[] temporizador = {new Timer(500, null)}; // Declaração final e inicialização do Timer
        int[] contador = {0}; // contador para controlar o número de vezes que a label piscou
        temporizador[0] = new Timer(500, (ActionEvent e) -> {
            outputPG.setVisible(!outputPG.isVisible()); // Inverte a visibilidade da JLabel
            contador[0]++; // Incrementa o contador
            if (contador[0] >= 10) { // Se a label piscar 10 vezes
                temporizador[0].stop(); // Para o temporizador
            }
        });
        temporizador[0].start();    
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalculo;
    private javax.swing.JRadioButton botaoHomem;
    private javax.swing.JRadioButton botaoMulher;
    private javax.swing.JTextField circCintura;
    private javax.swing.JTextField circPescoco;
    private javax.swing.JTextField circQuadril;
    private javax.swing.ButtonGroup grupoBotoesTipo;
    private javax.swing.JTextField inputAltura;
    private javax.swing.JTextField inputPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelCentimetros;
    private javax.swing.JLabel labelCircCintura;
    private javax.swing.JLabel labelCircPescoco;
    private javax.swing.JLabel labelCircQuadril;
    private javax.swing.JLabel labelKilogramas;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JTextArea outputInfoPG;
    private javax.swing.JLabel outputPG;
    private javax.swing.JButton voltarMenu;
    // End of variables declaration//GEN-END:variables
}
